# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: smollm.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'smollm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csmollm.proto\x12\x06smollm\"\x1b\n\tSmolLMReq\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"I\n\tSmolLMRes\x12\x10\n\x08\x63urToken\x18\x01 \x01(\t\x12\x10\n\x08tokenNum\x18\x02 \x01(\r\x12\x18\n\x10tokenProbability\x18\x03 \x01(\x02\x32;\n\x06smollm\x12\x31\n\x07sendReq\x12\x11.smollm.SmolLMReq\x1a\x11.smollm.SmolLMRes0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smollm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SMOLLMREQ']._serialized_start=24
  _globals['_SMOLLMREQ']._serialized_end=51
  _globals['_SMOLLMRES']._serialized_start=53
  _globals['_SMOLLMRES']._serialized_end=126
  _globals['_SMOLLM']._serialized_start=128
  _globals['_SMOLLM']._serialized_end=187
# @@protoc_insertion_point(module_scope)
